FROM quay.io/konflux-ci/yarn3-nodejs20-ubi9-minimal AS build

WORKDIR /usr/src/app
COPY . .
COPY LICENSE /licenses/

RUN yarn install && yarn build

FROM registry.access.redhat.com/ubi9/nginx-120:latest

# Values for below ARGs will be passed from tekton configs for konflux builds.
## Release version of the ocp-secrets-management-console source code used in the build.
ARG RELEASE_VERSION
## Commit hash that considered for the image build.
ARG COMMIT_SHA
## GitHub URL of the ocp-secrets-management-console source repository.
ARG SOURCE_URL

COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY --from=build /licenses /licenses

USER 1001

LABEL com.redhat.component="ocp-secrets-management-console-container" \
 cpe="cpe:/a:redhat:secrets_management_console:0.1::el9" \
 name="secrets-management-console/ocp-secrets-management-rhel9" \
 version="${RELEASE_VERSION}" \
 summary="ocp-secrets-management-console" \
 maintainer="Red Hat, Inc." \
 description="ocp-secrets-management-console-container" \
 vendor="Red Hat, Inc." \
 release="${RELEASE_VERSION}" \
 io.openshift.expose-services="" \
 io.openshift.tags="data,images,ocp-secrets-management,secrets-management-console" \
 distribution-scope="public" \
 url="${SOURCE_URL}" \
 io.openshift.build.commit.id="${COMMIT_SHA}" \
 io.openshift.build.source-location="${SOURCE_URL}" \
 io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
 io.openshift.maintainer.product="OpenShift Container Platform" \
 io.k8s.display-name="ocp-secrets-management-console" \
 io.k8s.description="ocp-secrets-management-console-container"

ENTRYPOINT ["nginx", "-g", "daemon off;"]
