apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: console-plugin-operator-bundle-0-1-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[release-0.1]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "release-0.1" &&
      ("operator/bundle/***".pathChanged() || "operator/bundle.Dockerfile".pathChanged())
    build.appstudio.openshift.io/repo: "https://github.com/openshift/ocp-secrets-management-console?rev={{revision}}"
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
  labels:
    appstudio.openshift.io/application: console-plugin-operator-0-1
    appstudio.openshift.io/component: console-plugin-operator-bundle-0-1
    pipelines.appstudio.openshift.io/type: build
spec:
  params:
    - name: dockerfile
      value: operator/bundle.Dockerfile
    - name: git-url
      value: "{{source_url}}"
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/secrets-management-console-tenant/console-plugin-operator-bundle-release:on-pr-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: "{{revision}}"
  pipelineRef:
    name: docker-build-oci-ta
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
